### ISSUE TITLE
Suppot for different docker.sock location 

### ISSUE THREAD

**Issue by daeho-ro** [robertpsoane/ducker#19]
**Is your feature request related to a problem? Please describe.**
It seems that the ducker is not working on MacOS.
Install rust by brew and build by cargo with 3 warnings but the binary is not working and there is no error messages.

I am using M3 sonoma 14.3.1, and uses the Warp as terminal.

**Describe the solution you'd like**
Don't know about rust.

**Describe alternatives you've considered**

**Additional context**

**Comment by robertpsoane** [comment]
Thanks for raising this!

While Ducker hasn't explicitly been tested on MacOS (I don't own a Mac) I have seen it work on a Mac before so I _think_ there should already be certain degree of support for Mac.

So you have a screenshot of what happened when you tried to run ducker?

And can you post the output of `ls /var/run | grep docker`?  I want to check the docker socket is present in the default place.

**Comment by daeho-ro** [comment]
Oh, I found the `docker.sock` from `~/.docker/run`. Maybe this is for using a user only not system.

**Comment by robertpsoane** [comment]
Ah amazing! Thanks very much!

I will add a cli arg and config for overriding the docker.sock defaults it's currently using

**Comment by robertpsoane** [comment]
I've merged what should be a fix - this is currently unreleased, but if you install from the repo with the command below it should work.

If you run ducker with `--docker-path`/`-d` then it should work

This is also configurable via the config

Hopefully the error message is more useful now too!

```bash
cargo install --locked --git https://github.com/robertpsoane/ducker
```
